### ISSUE TITLE
Please support for firebase_database 11.x

### ISSUE THREAD

**Issue by Seyun** [sitatec/firebase_database_mocks#17]
As realtime database version has upgraded to 11, please support this.

**Comment by sitatec** [comment]
Thanks for the remainder, I will work on it as soon as I get some free time. PRs are also welcome :)

**Comment by AngeloAvv** [comment]
#19

**Comment by SyncroIT** [comment]
Any updates?

**Comment by sitatec** [comment]
✅  https://github.com/sitatec/firebase_database_mocks/releases/tag/v0.7.0
