### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by SamuMazzi** [sitatec/firebase_database_mocks#3]
Can you please update the dependencies to make it works with the latest version of firebase_database?

> Because firebase_database_mocks >=0.2.0+1 depends on firebase_database ^7.2.1 and "project" depends on firebase_database ^8.0.0, firebase_database_mocks >=0.2.0+1 is forbidden.

Thank you!

**Comment by sitatec** [comment]
Hi @SamuMazzi! 
Thank you for the reminder.

I have published [a new release](https://github.com/sitatec/firebase_database_mocks/releases/tag/v0.3.0) that supports firebase_database ^9.0.3.
But still need to upgrade firebase_database from your side since you are using the version ^8.0.0.

**Comment by SamuMazzi** [comment]
Sure, thank you!
