### ISSUE TITLE
Make data non-static field so it's easier to write atomic tests

### ISSUE THREAD

**Issue by Zohenn** [sitatec/firebase_database_mocks#9]
It is considered a good practice to write tests that are atomic. This means that tests will not behave differently when run individually, together, in random order, etc. Currently data is stored as a static field on ```MockDatabaseReference```, and that means that it will never be automatically cleared for all tests in current run.

As a workaround you can call ```set(null)``` on root reference in ```setUp``` block, though ideally you should be able to create a new ```MockFirebaseDatabase``` instance for every test. Data would be stored on that instance and passed down to ```MockDatabaseReference``` in constructor.

What do you think @sitatec? I can make a PR, and after that I would try to implement ```update``` or other methods.

**Comment by sitatec** [comment]
@Zohenn you actually can decide to keep data between multiple instances or make each instance have their own data store `MockFirebaseDatabase.setDataPersistenceEnabled(enabled: false)` but non-persistent mode have not been tested well, actually.

You can look at  `MockDatabaseReference` implementation:
```dart
  static Map<String, dynamic>? _persistedData = <String, dynamic>{};
  Map<String, dynamic>? _volatileData = <String, dynamic>{};

  Map<String, dynamic>? get _data {
    if (MockFirebaseDatabase.persistData) {
      return _persistedData;
    }
    return _volatileData;
  }

  set _data(data) {
    if (MockFirebaseDatabase.persistData) {
      _persistedData = data;
    } else
      return _volatileData = data;
  }
```

**Comment by Zohenn** [comment]
The problem is that when using this option, data is stored on given reference, not database instance, and you will probably be creating many references. Even though you pass it down when using ```child()```, if you were to create a fresh reference from root using ```MockFirebaseDatabase.ref()```, you will end up with empty data. And I'm pretty sure you would agree, that this should not be the case.

My solution would be to move ```_volatileData``` from ```MockDatabaseReference``` to ```MockFirebaseDatabase```, and then pass it down to children right away when using ```ref()```. The rest would stay pretty much the same, what do you think?

As a side note, I would also consider changing the default mode to the 'non-persistent' one, as I believe this is what most people would expect.

**Comment by sitatec** [comment]
Make sense, you can open a PR for it. 👍
